### ISSUE TITLE
Exception thrown

### ISSUE THREAD

**Issue by Hipapheralkus** [bao7uo/waf-cookie-fetcher#6]
Hi,
I wanted Empty the whole cookie jar within the session handling rule:
![image](https://user-images.githubusercontent.com/4717664/40547366-fe28ea54-6031-11e8-8e8d-cd6272b58acd.png)

but then I saw an exception thrown in the Session Handler:

![image](https://user-images.githubusercontent.com/4717664/40547295-d27d4710-6031-11e8-809f-e0911ea8284d.png)

Error trace:
```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\BurpSuite\bapps\0f6ce51c1cb349689ecb4025e8db060a\waf-cookie-fetcher.py", line 349, in performAction
    cookies_to_remove_names = self.cookies_to_remove.getNames()
AttributeError: 'SHA_Remove_Cookies' object has no attribute 'cookies_to_remove'

	at org.python.core.Py.AttributeError(Py.java:205)
	at org.python.core.PyObject.noAttributeError(PyObject.java:1013)
	at org.python.core.PyObject.__getattr__(PyObject.java:1008)
	at org.python.pycode._pyx4.performAction$38(C:\Users\user\AppData\Roaming\BurpSuite\bapps\0f6ce51c1cb349689ecb4025e8db060a\waf-cookie-fetcher.py:351)
	at org.python.pycode._pyx4.call_function(C:\Users\user\AppData\Roaming\BurpSuite\bapps\0f6ce51c1cb349689ecb4025e8db060a\waf-cookie-fetcher.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3626)
	at org.python.core.PyObject._jcall(PyObject.java:3658)
	at org.python.proxies.__main__$SHA_Remove_Cookies$6.performAction(Unknown Source)
	at burp.l0c.a(Unknown Source)
	at burp.xx.a(Unknown Source)
	at burp.zx.a(Unknown Source)
	at burp.dy.a(Unknown Source)
	at burp.qyi.a(Unknown Source)
	at burp.fhf.a(Unknown Source)
	at burp.fhf.a(Unknown Source)
	at burp.fhf.a(Unknown Source)
	at burp.k4b.l(Unknown Source)
	at burp.k4b.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

```
Thanks

**Comment by bao7uo** [comment]
I will look into this.

**Comment by mchu519** [comment]
Any update on this?  I encounter the exact same issue.

**Comment by kgarmin** [comment]
Any update? I've had the same issue for over a year:(
